apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongobd-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: mongodb-service
  replicas: 1
  template:
    metadata:
      labels:
        run: mongodb-service
    spec:
      containers:
      - name: helm-service
        image: jbraeuer/mongodb-service:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: keptn
  labels:
    run: mongodb-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: mongodb-service
