apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongobd-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: mongodb-service
  replicas: 1
  template:
    metadata:
      labels:
        run: mongodb-service
    spec:
      containers:
      - name: mongodb-service
        image: jbraeuer/mongodb-service:0.0.2
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /data/dumpdir
          name: mongodb-dump-volume
        env:
        - name: DUMP_DIR_ONE_COLLECTION
          value: '/data/dumpdir/dumpDirOneCollection'
        - name: DUMP_DIR_MULTIPLE_COLLECTIONS
          value: '/data/dumpdir/dumpDirMultipleCollections'
        - name: DUMP_DIR_ALL_COLLECTIONS
          value: '/data/dumpdir/dumpDirAllCollections'
      volumes:
      - name: mongodb-dump-volume
        persistentVolumeClaim:
          claimName: mongodb-dump-volume
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: keptn
  labels:
    run: mongodb-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: mongodb-service
